services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: wedding_gifts
      PORT: 3001
      PAYMENT_PROVIDER: asaas
      WEBHOOK_SECRET: change-me-in-production
      ASAAS_API_KEY: "$$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjYwYzEzZDQ5LTA4MDktNGYxMi04NWFkLTE2N2Q0OGE5MDVlNTo6JGFhY2hfMDM2MjJhMWItY2UxOS00YjkwLWE1ZDAtZjcwYjBkNTE1ZjBh"
      ASAAS_AUTH_TOKEN: whsec_JHJLAUa7s5iG4XoKbJmUZg6gKWKm_z_AzvbIiCoPJWs
      ASAAS_API_URL: https://api-sandbox.asaas.com/v3
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedding_gifts
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
